### ISSUE TITLE
Import into Anki without translating

### ISSUE THREAD

**Issue by silentjay** [prz3m/kind2anki#1]
Would it be possible to disable the translate option so you can use the plugin to do a standard import?

Update: Ah never mind I thought each word you have in the vocab builder would also have it's dictionary definition available in the vocab.db but it isn't

**Comment by prz3m** [comment]
Hi, I added "Translate words" checkbox.

Unfortunately, I don't know how to check definitions in dictionary in Kindle. It would be much faster than using Google Translate.
